### ISSUE TITLE
Curve Fitting Errors with HIV Neutralization Assays

### ISSUE THREAD

**Issue by kmalone2** [jbloomlab/neutcurve#12]
I've compiled a case where the neutcurve package is not able to fit a curve to a particular set of neutralization data. I also included a reference case where a line is being fit, but is centered at 1. The attached [TZMNeutAssaysTesting.ipynb.zip](https://github.com/jbloomlab/neutcurve/files/3370471/TZMNeutAssaysTesting.ipynb.zip) contains some data where this package isn't working.

**Comment by jbloom** [comment]
@kmalone2:

I think I have fixed the problem by adding an option to try a second fitting method for problematic curves. This is done on the [hiv-curve-bug](https://github.com/jbloomlab/neutcurve/tree/hiv-curve-bug) branch.

Can you see if these changes fix the problem? In order to install the new version, do the following:

      git clone -b hiv-curve-bug https://github.com/jbloomlab/neutcurve  # clone the branch with the fix
      cd neutcurve  # go into the cloned branch
      python setup.py install --user   # install for yourself locally

After doing this, open your Jupyter notebook with the HIV curves and try them out. Note that you should ensure that you have a `neutcurve` version of 0.2.5 running in your notebook with:

      import neutcurve
      print(neutcurve.__version__) 

Let me know if this fixes the problem, and if so I'll merge the branch into the main repo.

**Comment by kmalone2** [comment]
@jbloom It's working now, thank you!

**Comment by jbloom** [comment]
Fixed in commit a37338.

@kmalone2: The new version on the `BloomLab_v3` should now work. If you want to use that and uninstall your local version you built as above, you can do:

      rm -rf ~/.local

(Note this will delete any other local installations if you have those too).
